### ISSUE TITLE
OpenLiteSpeed WordPress MariaDB replace to MySQL 8

### ISSUE THREAD

**Issue by sufiaakter19** [litespeedtech/ols1clk#45]
MariaDB
[10.4](https://mariadb.org/)
[GPL](https://mariadb.com/kb/en/library/mariadb-license/)

https://marketplace.digitalocean.com/apps/openlitespeed-wordpress

How can I use MySQL 8

**Comment by Code-Egg** [comment]
You could check https://www.digitalocean.com/community/questions/how-to-migrate-from-maria-db-to-mysql-8

**Comment by ltroya-as** [comment]
My two cents

These are the changes I made to support MySQL 8 on my setup:

`docker-compose.yml`
```
 mysql:
    image: amd64/mysql:8.0.28
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./data/mysql:/var/lib/mysql:delegated"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
```

And changed this line on `bin/database.sh`

```
-e "GRANT ALL PRIVILEGES ON '${SQL_DB}'.* TO '${SQL_USER}'@'${ANY}' IDENTIFIED BY '${SQL_PASS}';" \
```

To

```
-e "CREATE USER '${SQL_DB}'@'${ANY}' IDENTIFIED BY '$SQL_PASS';" \
 -e "GRANT ALL ON '${SQL_DB}'.* TO '${SQL_USER}'@'${ANY}';" \
```

To former line gave some troubles when adding a user and a database.
